### ISSUE TITLE
Submit Your Creative  projects here

### ISSUE THREAD

**Issue by vijaygupta18** [vijaygupta18/Hacktober-2020#13]
This is open repo for everyone to contribute anything you have made.
Even small valid contribution will be considered.

>### project

**Comment by Aravindha1234u** [comment]
@vijaygupta18 Can you assign this to me I will submit me Instagram public account scraper with python and graphql

**Comment by vijaygupta18** [comment]
> @vijaygupta18 Can you assign this to me I will submit me Instagram public account scraper with python and graphql

yeah done!!!

**Comment by Maaz-Code** [comment]
Hello there!! Can you review my request to merge my pull request? I have added a folder as Rock Paper Scissors. Happy Hacktober Fest 2020.

**Comment by vijaygupta18** [comment]
> Hello there!! Can you review my request to merge my pull request? I have added a folder as Rock Paper Scissors. Happy Hacktober Fest 2020.

Yeah that was good..Keep learning 🤘

**Comment by 26Vinayak** [comment]
I want to contribute in  this repository any one assign me this issue?

**Comment by vijaygupta18** [comment]
> I want to contribute in this repository any one assign me this issue?

merged🤘... Happy hacking.

**Comment by Maaz-Code** [comment]
Hey @vijaygupta18 . I have contributed two times now. Can I contribute more?

**Comment by vijaygupta18** [comment]
> Hey @vijaygupta18 . I have contributed two times now. Can I contribute more?

Yes you can contribute.

**Comment by DenseOriginal** [comment]
Hey, @vijaygupta18 can you check out me pull request for my snake game? Happy Hacktoberfest :))

**Comment by vijaygupta18** [comment]
> Hey, @vijaygupta18 can you check out me pull request for my snake game? Happy Hacktoberfest :))

yeah sure...done!!

**Comment by vijaygupta18** [comment]
Please don't Submit programs like printing hello world.
Try to do something more.
Learn and try again.
Happy coding 🤘

**Comment by Somsubhra1** [comment]
Hello @vijaygupta18 please check my bookmarkmanager project pr. Thanks and happy coding 👍

**Comment by vijaygupta18** [comment]
> Hello @vijaygupta18 please check my bookmarkmanager project pr. Thanks and happy coding 👍

merged 🤘
Give a Star ⭐ if you liked this repo

**Comment by shahkv95** [comment]
Hey, @vijaygupta18 Could you please assign this issue to me?
Thank you!

**Comment by vijaygupta18** [comment]
> Hey, @vijaygupta18 Could you please assign this issue to me?
> Thank you!

Yeah sure...This is open for all.

**Comment by vijaygupta18** [comment]
> Hey, @vijaygupta18 Could you please assign this issue to me?
> Thank you!

@shahkv95 Yeah sure... this  is open for all.

**Comment by Vivi3008** [comment]
Hello, could you take a look at my hacktoberfest project Matrix?

**Comment by vijaygupta18** [comment]
> Hello, could you take a look at my hacktoberfest project Matrix?

@Vivi3008 
project was fine
I merged it

**Comment by vijaygupta18** [comment]
> Hello, could you take a look at my hacktoberfest project Matrix?

Yeah sure..
Done!!
Keep learning and don't forget to add a 🌟

**Comment by NEENA-XAVIER** [comment]
I like to add a program to implement a calculator!

**Comment by vijaygupta18** [comment]
> I like to add a program to implement a calculator!

Okay do PR I'll look for it.

**Comment by AnshMishra2001** [comment]
Generated PR for simple alarm app

**Comment by chakshush** [comment]
created PR for different projects that i made

**Comment by vijaygupta18** [comment]
> Generated PR for simple alarm app

@AnshMishra2001 Accepted

**Comment by vijaygupta18** [comment]
> created PR for different projects that i made

@chakshush accepted 👍

**Comment by KaivalyaD** [comment]
Hi! Thanks, @vijaygupta18 for the opportunity! I have created a Pull Request for my project titled 'Secupi.' Please pull my project up the boat, as well. Happy Hacktober! :) 
#133

**Comment by vijaygupta18** [comment]
> Hi! Thanks, @vijaygupta18 for the opportunity! I have created a Pull Request for my project titled 'Secupi.' Please pull my project up the boat, as well. Happy Hacktober! :)
> #133

Merged 🤘

**Comment by Joe-Ralph** [comment]
> Hi! @vijaygupta18 I've added a ML project on Sentiment Analysis on text. Please approve my PR. ***Happy Hacking !***🐱‍💻

**Comment by vijaygupta18** [comment]
> > Hi! @vijaygupta18 I've added a ML project on Sentiment Analysis on text. Please approve my PR. _**Happy Hacking !**_ 🐱‍💻

done

**Comment by sebabratakundu** [comment]
Hi @vijaygupta18 I added a project on random password generator using javascript, bootstrap. please pull my request. Happy Hacktober!
#216

**Comment by vijaygupta18** [comment]
> Hi @vijaygupta18 I added a project on random password generator using javascript, bootstrap. please pull my request. Happy Hacktober!
> #216

Merged 🤘

**Comment by sebabratakundu** [comment]
Hi, @vijaygupta18 I added another project. it is a responsive random image gallery project, in which I used the CSS grid and ES6.
the image resources are from Unsplash.com. Happy Hacktober!
#220

**Comment by vijaygupta18** [comment]
> Hi, @vijaygupta18 I added another project. it is a responsive random image gallery project, in which I used the CSS grid and ES6.
> the image resources are from Unsplash.com. Happy Hacktober!
> #220

keep learning

**Comment by DipadityaDas** [comment]
Hi, @vijaygupta18 I added a Webpage with Happy Penguin Animation where I used simple CSS to build it. Happy Hacktober!
#239

**Comment by vijaygupta18** [comment]
> Hi, @vijaygupta18 I added a Webpage with Happy Penguin Animation where I used simple CSS to build it. Happy Hacktober!
> #239

merged
