### ISSUE TITLE
Automating movies and TV series search using python scripts

### ISSUE THREAD

**Issue by pyGitHub7** [vijaygupta18/Hacktober-2020#59]
IT IS A MINI-IMDB PROJECT THAT PROVIDES INFORMATION ABOUT ANY MOVIE OR TV SERIES WHEN SEARCHED.
This project is coded in python language and uses basics of python data structure - lists, OOPS and some basics of database.
Please assign!

**Comment by vijaygupta18** [comment]
Give a star for supporting

**Comment by vijaygupta18** [comment]
Assigned.
Keep up good work.
